name: build to github

on:
  push:
    branches: [ build-to-github ]

jobs:
  github-build-and-push:
    runs-on: ubuntu-latest

    # 실행 스텝 지정
    # https://github.com/marketplace/actions/build-with-gradle
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # java version 지정
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build


      # https://github.com/marketplace/actions/build-and-push-docker-images
      # 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 관련 설정 적용
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build 및 Push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: . # 지정하지 않으면 기본적으로 현재 디렉토리가 빌드 컨텍스트로 사용됩니다.
          file: ./docker/Dockerfile-github
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_TAG_NAME }}:latest